eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083

spring:
  application:
    name: transactions-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
myapp:
  api:
    base-url:
      accounts-service: http://account-service/api/v1/accounts/

      transactions-service: http://user-service/api/v1/users/