eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083

spring:
  application:
    name: transactions-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transactions-consumer-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

kafka:
  topic:
    transaction:
      creation: transaction-creation
      credit-account: credit-account
      credit-account-response: account-service-credit-response
      balance-update:
#        user-service: user-service-balance-update
        account-service: account-service-balance-update

myapp:
  api:
    base-url:
      account-service: http://account-service/api/v1/accounts/
      user-service: http://user-service/api/v1/users/